<?php

namespace Gopro\FitBundle\Repository;

/**
 * AlimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlimentoRepository extends \Doctrine\ORM\EntityRepository
{
}
