<?php

namespace Gopro\FitBundle\Repository;
use Gopro\UserBundle\Entity\User;
use SensioLabs\Security\Exception\HttpException;

/**
 * DietacomidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DietacomidaRepository extends \Doctrine\ORM\EntityRepository
{

}
