<?php

namespace Gopro\FitBundle\Repository;

/**
 * DietaalimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DietaalimentoRepository extends \Doctrine\ORM\EntityRepository
{
}
