services:
    gopro_user.admin.organizacion:
        class: Gopro\UserBundle\Admin\OrganizacionAdmin
        arguments: [~, Gopro\UserBundle\Entity\Organizacion, GoproUserBundle:OrganizacionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: Organizaciones}

    gopro_user.admin.dependencia:
        class: Gopro\UserBundle\Admin\DependenciaAdmin
        arguments: [~, Gopro\UserBundle\Entity\Dependencia, GoproUserBundle:DependenciaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: Dependencias}

    gopro_user.admin.area:
        class: Gopro\UserBundle\Admin\AreaAdmin
        arguments: [~, Gopro\UserBundle\Entity\Area, GoproUserBundle:AreaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: Areas}

    gopro_user.admin.cuenta:
            class: Gopro\UserBundle\Admin\CuentaAdmin
            arguments: [~, Gopro\UserBundle\Entity\Cuenta, GoproUserBundle:CuentaAdmin]
            tags:
                - {name: sonata.admin, manager_type: orm, group: Admin, label: 'Cuenta de usuario'}

    gopro_user.admin.cuentatipo:
                class: Gopro\UserBundle\Admin\CuentatipoAdmin
                arguments: [~, Gopro\UserBundle\Entity\Cuentatipo, GoproUserBundle:CuentatipoAdmin]
                tags:
                    - {name: sonata.admin, manager_type: orm, group: Admin, label: "Tipos de cuentas"}

