services:
    gopro_main.archivozip:
        class: Gopro\MainBundle\Service\Archivozip
        calls:
            - [ setContainer,[ "@service_container" ] ]
            - [ setVariableproceso,[ "@gopro_main.variableproceso" ] ]
        shared: false
    gopro_main.archivoexcel:
        class: Gopro\MainBundle\Service\Archivoexcel
        calls:
            - [ setContainer,[ "@service_container" ] ]
            - [ setVariableproceso,[ "@gopro_main.variableproceso" ] ]
        shared: false
    gopro_main.variableproceso:
        class: Gopro\MainBundle\Service\Variableproceso
        calls:
            - [ setContainer,[ "@service_container" ] ]