<?php

namespace Gopro\CotizacionBundle\Repository;

/**
 * CotcomponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotcomponenteRepository extends \Doctrine\ORM\EntityRepository
{
}
