<?php

namespace Gopro\CotizacionBundle\Repository;

/**
 * CotservicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotservicioRepository extends \Doctrine\ORM\EntityRepository
{
}
