<?php

namespace Gopro\CotizacionBundle\Repository;

/**
 * CottarifaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CottarifaRepository extends \Doctrine\ORM\EntityRepository
{
}
