<?php

namespace Gopro\CotizacionBundle\Repository;

/**
 * FilepasajeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiledocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
