gopro_servicio:
    resource: "@GoproServicioBundle/Controller/"
    type:     annotation
    prefix:   /servicio

gopro_main:
    resource: "@GoproMainBundle/Controller/"
    type:     annotation
    prefix:   /

gopro_cotizacion:
    resource: "@GoproCotizacionBundle/Controller/"
    type:     annotation
    prefix:   /cotizacion

gopro_maestro:
    resource: "@GoproMaestroBundle/Controller/"
    type:     annotation
    prefix:   /maestro

gopro_transporte:
    resource: "@GoproTransporteBundle/Controller/"
    type:     annotation
    prefix:   /transporte

gopro_fullcalendar:
    resource: "@GoproFullcalendarBundle/Controller/"
    type:     annotation
    prefix:   /fullcalendar

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

# error-prevention
homepage:
    path: /
