parameters:
    archivo.class:  Gopro\Vipac\CargadorBundle\Comun\Archivo
    cargador.class:  Gopro\Vipac\CargadorBundle\Comun\Cargador
    variable.class:  Gopro\Vipac\CargadorBundle\Comun\Variable

services:
    gopro_comun_archivo:
        class: %archivo.class%
        calls:
            - [ setContainer,[ @service_container ] ]
    gopro_comun_cargador:
        class: %cargador.class%
        calls:
            - [ setContainer,[ @service_container ] ]
    gopro_comun_variable:
        class: %variable.class%
        calls:
            - [ setContainer,[ @service_container ] ]

