<?php

namespace Gopro\CuentaBundle\Repository;

/**
 * CentroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroRepository extends \Doctrine\ORM\EntityRepository
{
}
