services:

    gopro_transporte.admin.servicio:
        class: Gopro\TransporteBundle\Admin\ServicioAdmin
        arguments: [~, Gopro\TransporteBundle\Entity\Servicio, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Transporte, label: Servicios}
        calls:
            - [ setTemplate, [list, GoproTransporteBundle:ServicioAdmin:list.html.twig]]
            - [ setTemplate, [edit, GoproTransporteBundle:ServicioAdmin:edit.html.twig]]
        public: true

    gopro_transporte.admin.serviciooperativo:
        class: Gopro\TransporteBundle\Admin\ServiciooperativoAdmin
        arguments: [~, Gopro\TransporteBundle\Entity\Serviciooperativo, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: Transporte, label: Operativos}
        public: true

    gopro_transporte.admin.serviciocontable:
        class: Gopro\TransporteBundle\Admin\ServiciocontableAdmin
        arguments: [~, Gopro\TransporteBundle\Entity\Serviciocontable, GoproTransporteBundle:ServiciocontableAdmin ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Transporte, label: Contables}
        calls:
            - [ setTemplate, [edit, GoproTransporteBundle:ServiciocontableAdmin:edit.html.twig]]
        public: true

    gopro_transporte.admin.serviciocomponente:
        class: Gopro\TransporteBundle\Admin\ServiciocomponenteAdmin
        arguments: [~, Gopro\TransporteBundle\Entity\Serviciocomponente, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: Transporte, label: Files}
        public: true

    gopro_transporte.admin.conductor:
        class: Gopro\TransporteBundle\Admin\ConductorAdmin
        arguments: [~, Gopro\TransporteBundle\Entity\Conductor, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Transporte, label: Conductores}
        public: true

    gopro_transporte.admin.unidad:
        class: Gopro\TransporteBundle\Admin\UnidadAdmin
        arguments: [~, Gopro\TransporteBundle\Entity\Unidad, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Transporte, label: Unidades}
        public: true

    gopro_transporte.admin.tiposeroperativo:
        class: Gopro\TransporteBundle\Admin\TiposeroperativoAdmin
        arguments: [~, Gopro\TransporteBundle\Entity\Tiposeroperativo, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Transporte, label: Tipo operativo}
        public: true

    gopro_transporte.admin.tipounibit:
        class: Gopro\TransporteBundle\Admin\TipounibitAdmin
        arguments: [~, Gopro\TransporteBundle\Entity\Tipounibit, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Transporte, label: Tipo de bitácora}
        public: true

    gopro_transporte.admin.unidadbitacora:
        class: Gopro\TransporteBundle\Admin\UnidadbitacoraAdmin
        arguments: [~, Gopro\TransporteBundle\Entity\Unidadbitacora, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Transporte, label: Bitácoras}
        public: true

