<?php

namespace Gopro\ServicioBundle\Repository;

/**
 * ComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItidiaarchivoRepository extends \Doctrine\ORM\EntityRepository
{
}
