<?php

namespace Gopro\ServicioBundle\Repository;

/**
 * ItinerariodiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItinerariodiaRepository extends \Doctrine\ORM\EntityRepository
{
}
