<?php

namespace Gopro\ServicioBundle\Repository;

/**
 * TarifaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifaRepository extends \Doctrine\ORM\EntityRepository
{
}
