<?php

namespace Gopro\ServicioBundle\Repository;

/**
 * TipocomponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipocomponenteRepository extends \Doctrine\ORM\EntityRepository
{
}
