services:
    gopro_maestro.admin.moneda:
        class: Gopro\MaestroBundle\Admin\MonedaAdmin
        arguments: [~, Gopro\MaestroBundle\Entity\Moneda, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Maestros, label: Monedas}

    gopro_maestro.admin.tipocambio:
            class: Gopro\MaestroBundle\Admin\TipocambioAdmin
            arguments: [~, Gopro\MaestroBundle\Entity\Tipocambio, ~]
            tags:
                - {name: sonata.admin, manager_type: orm, group: Maestros, label: Tipo de cambio}
